### ISSUE TITLE
future::remote: Use case? Can you use future::cluster instead?

### ISSUE THREAD

**Issue by HenrikBengtsson** [mkoohafkan/reval#5]
Hi, I'm cleaning up the **future** API and one thing I'm looking into is to deprecate `remote` (https://github.com/HenrikBengtsson/future/issues/581), especially since `cluster` has become more powerful over the years with smarter defaults, and it can connect to remote machines out of the box.  `remote` was introduced in the very early days.  

I spotted that you import and re-export it in your package.  I'm curious about your use case.  Could you equally well use `plan(cluster, ...)`?

**Comment by mkoohafkan** [comment]
I just reexported all of the plan types those for convenience. Totally unnecessary, I can just drop the plan reexports alltogether. Frankly I'm considering just retiring this package completely as I don't think it provides much value anymore (I wrote it long before future and furrr and only recently changed it to use furrr and future as the backend).

**Comment by HenrikBengtsson** [comment]
Thanks for the quick response. This helps me to move forward in deprecating `remote`.  

For now, that's just a run-time deprecation warning, so it won't affect your package on CRAN.  Also, I doubt your package would be impacted even for the next step when I turn that deprecation warning into a defunct error in 3-6 months from now.  It'll only impact users trying to use `plan(remote, ...)`.  It's only when I remove `remote` from the **future** API that your package will be affected.

PS. Don't underestimate the value of your package/API. I have some old packages, and I'm equally surprised, and happy, whenever I hear someone out there is still relying on them in their work.

**Comment by HenrikBengtsson** [comment]
FWIW, 'transparent' will also be deprecated in future (>= 1.24.0), cf. https://github.com/HenrikBengtsson/future/issues/547
